# Generated by Django 2.0.1 on 2018-11-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicEnv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicestatus',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='servicestatus',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
