# Generated by Django 2.0.1 on 2018-11-27 09:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publicEnv', '0003_servicest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicest',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='servicest',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
