# Generated by Django 2.0.1 on 2018-11-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicEnv', '0004_auto_20181127_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicest',
            name='create_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='servicest',
            name='update_time',
            field=models.DateTimeField(),
        ),
    ]
