# Generated by Django 2.0.1 on 2018-12-07 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_auto_20180814_1419'),
        ('publicEnv', '0007_auto_20181207_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyhost',
            name='user_fk',
        ),
        migrations.RemoveField(
            model_name='analydetail',
            name='h',
        ),
        migrations.AddField(
            model_name='analydetail',
            name='user_fk',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='rbac.UserInfo', to_field='username'),
        ),
        migrations.DeleteModel(
            name='AnalyHost',
        ),
    ]
