# Generated by Django 2.0.1 on 2018-12-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicEnv', '0008_auto_20181207_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='analydetail',
            name='base_interval',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='analydetail',
            name='basep',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='analydetail',
            name='test_interval',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='analydetail',
            name='testp',
            field=models.CharField(default='', max_length=10),
        ),
    ]
