# Generated by Django 2.0.1 on 2018-12-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicEnv', '0009_auto_20181210_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='analydetail',
            name='baseres_detail',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='analydetail',
            name='testres_detail',
            field=models.TextField(default=''),
        ),
    ]
