# Generated by Django 2.0.1 on 2018-12-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicEnv', '0010_auto_20181211_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='analydetail',
            name='basebox',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='analydetail',
            name='testbox',
            field=models.CharField(default='', max_length=10),
        ),
    ]
