# Generated by Django 2.1.2 on 2018-12-17 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicEnv', '0011_auto_20181213_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=256)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('alias', models.CharField(max_length=200)),
                ('domain', models.TextField()),
                ('start_urls', models.TextField()),
                ('user_agents', models.TextField(default='Mozilla/5.0 (Windows NT 6.1; WOW64; rv:34.0) Gecko/20100101 Firefox/34.0')),
                ('pipelines', models.CharField(max_length=100)),
                ('download_delay', models.IntegerField(default=3)),
                ('image_urls', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.CharField(blank=True, max_length=50, null=True)),
                ('md5', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.IntegerField(choices=[(0, '构建中'), (1, '初始化'), (2, '运行'), (3, '停止')], default=0)),
                ('is_public', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=256)),
                ('callback_func', models.CharField(blank=True, max_length=50, null=True, verbose_name='回调')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publicEnv.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Special_check_deadlink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('imgurl', models.CharField(max_length=255)),
                ('add_timestamp', models.DateTimeField(auto_now=True)),
                ('error_count', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('vrid', models.IntegerField(default=0)),
                ('last_timestamp', models.DateTimeField(auto_now_add=True)),
                ('status_code', models.IntegerField(default=0)),
                ('type', models.IntegerField(default=0)),
                ('comment', models.TextField(default='')),
                ('query', models.CharField(default='', max_length=50)),
                ('ua_type', models.IntegerField(default=0)),
                ('vr_name', models.CharField(default='', max_length=255)),
                ('principal', models.CharField(default='', max_length=255)),
                ('re_check_fail', models.IntegerField(default=0)),
                ('manual_pass', models.IntegerField(default=0)),
                ('uuid', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'special_check_deadlink',
                'ordering': ['-error_count'],
            },
        ),
        migrations.AddField(
            model_name='field',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publicEnv.Rule'),
        ),
    ]
