# Generated by Django 2.1.2 on 2018-12-18 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicEnv', '0012_auto_20181217_1529'),
        ('publicEnv', '0012_auto_20181215_1037'),
    ]

    operations = [
    ]
