# Generated by Django 2.1.2 on 2018-12-18 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicEnv', '0013_merge_20181218_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='rule',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='project',
        ),
        migrations.DeleteModel(
            name='Field',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Rule',
        ),
    ]
