# Generated by Django 2.0.1 on 2018-08-21 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbac', '0003_auto_20180814_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='GpuMonitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.CharField(default='', max_length=50)),
                ('end_time', models.CharField(default='', max_length=50)),
                ('user', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=0)),
                ('monitorip', models.CharField(default='', max_length=500)),
                ('monitoruser', models.CharField(default='', max_length=500)),
                ('monitorpassw', models.CharField(default='', max_length=500)),
                ('gpumem', models.TextField(default='')),
                ('gpumemused', models.TextField(default='')),
                ('gpumem_list', models.TextField(default='')),
                ('gpumemused_list', models.TextField(default='')),
                ('gpuid', models.IntegerField(default=0)),
                ('errorlog', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('user', models.CharField(default='', max_length=500)),
                ('passw', models.CharField(default='', max_length=500)),
                ('status', models.IntegerField(default=0)),
                ('runningPID', models.CharField(default='', max_length=20)),
                ('gpuid', models.IntegerField(default=0)),
                ('processname', models.TextField(default='')),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.UserInfo', to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='ManEval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.CharField(default='', max_length=50)),
                ('start_time', models.CharField(default='', max_length=50)),
                ('end_time', models.CharField(default='', max_length=50)),
                ('user', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=0)),
                ('hubcfgip', models.CharField(default='', max_length=500)),
                ('hubcfguser', models.CharField(default='', max_length=500)),
                ('hubcfgpassw', models.CharField(default='', max_length=500)),
                ('hubcfgpath', models.CharField(default='', max_length=500)),
                ('hubdatapath', models.CharField(default='', max_length=500)),
                ('sercfgip', models.CharField(default='', max_length=500)),
                ('sercfguser', models.CharField(default='', max_length=500)),
                ('sercfgpassw', models.CharField(default='', max_length=500)),
                ('sercfgpath', models.CharField(default='', max_length=500)),
                ('serdatapath', models.CharField(default='', max_length=500)),
                ('queryip', models.CharField(default='', max_length=500)),
                ('queyruser', models.CharField(default='', max_length=500)),
                ('querypassw', models.CharField(default='', max_length=500)),
                ('querypath', models.CharField(default='', max_length=500)),
                ('runningIP', models.CharField(default='', max_length=50)),
                ('hubsvn', models.TextField(default='')),
                ('sersvn', models.TextField(default='')),
                ('errorlog', models.TextField(default='')),
                ('testtag', models.CharField(default='', max_length=500)),
                ('finished', models.IntegerField(default=0)),
                ('diffnum', models.IntegerField(default=0)),
                ('fromlan', models.CharField(default='', max_length=20)),
                ('tolan', models.CharField(default='', max_length=20)),
                ('isfromzh', models.CharField(default='', max_length=10)),
                ('lan_sel', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ManEvalDiff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.CharField(default='', max_length=50)),
                ('user', models.CharField(max_length=50)),
                ('diff_content', models.TextField(default='')),
                ('diff_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fanyi.ManEval')),
            ],
        ),
        migrations.CreateModel(
            name='ReqInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_ip', models.CharField(max_length=128)),
                ('trans_direct', models.CharField(max_length=20)),
                ('isfromzh', models.CharField(max_length=10)),
                ('req_text', models.CharField(max_length=2000)),
                ('result', models.CharField(max_length=2000)),
                ('reqtype', models.CharField(max_length=20)),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.UserInfo', to_field='username')),
            ],
        ),
        migrations.AddField(
            model_name='gpumonitor',
            name='h',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fanyi.Host'),
        ),
    ]
