# Generated by Django 2.0.1 on 2018-08-14 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbac', '0003_auto_20180814_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReqInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_ip', models.CharField(max_length=128)),
                ('trans_direct', models.CharField(max_length=20)),
                ('isfromzh', models.CharField(max_length=10)),
                ('req_text', models.CharField(max_length=2000)),
                ('result', models.CharField(max_length=2000)),
                ('reqtype', models.CharField(max_length=20)),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.UserInfo', to_field='username')),
            ],
        ),
    ]
