# Generated by Django 2.0.1 on 2018-08-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanyi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqinfo',
            name='req_text',
            field=models.TextField(default=''),
        ),
    ]
