# Generated by Django 2.0.1 on 2018-08-23 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanyi', '0003_reqinfo_reqfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqinfo',
            name='reqfield',
            field=models.CharField(default='', max_length=20),
        ),
    ]
