# Generated by Django 2.0.1 on 2018-08-23 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanyi', '0004_auto_20180823_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reqinfo',
            old_name='result',
            new_name='oriresult',
        ),
    ]
