# Generated by Django 2.0.1 on 2018-08-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanyi', '0005_auto_20180820_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpumonitor',
            name='gpuid',
            field=models.IntegerField(default=0),
        ),
    ]
