# Generated by Django 2.0.1 on 2018-08-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanyi', '0006_gpumonitor_gpuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='processname',
            field=models.TextField(default=''),
        ),
    ]
