# Generated by Django 2.0.1 on 2018-10-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanyi', '0006_reqinfo_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='reqinfo',
            name='json_chn_query',
            field=models.CharField(default='', max_length=256),
        ),
    ]
