# Generated by Django 2.0.1 on 2018-11-01 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanyi', '0008_interfacediff'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InterfaceDiff',
            new_name='InterfaceEval',
        ),
    ]
