# Generated by Django 2.0.1 on 2018-11-02 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fanyi', '0009_auto_20181101_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='IfEvalDiff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.CharField(default='', max_length=50)),
                ('user', models.CharField(max_length=50)),
                ('diff_content', models.TextField(default='')),
                ('diff_type', models.CharField(default='', max_length=30)),
                ('diff_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fanyi.InterfaceEval')),
            ],
        ),
    ]
