# Generated by Django 2.0.1 on 2018-08-21 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbac', '0003_auto_20180814_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebugQw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_ip', models.CharField(max_length=128)),
                ('exp_id', models.CharField(max_length=8)),
                ('query_from', models.CharField(default='', max_length=4)),
                ('query', models.CharField(max_length=2000)),
                ('result', models.CharField(max_length=2000)),
                ('c_time', models.DateTimeField(auto_now=True)),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.UserInfo', to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='Diff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.CharField(default='', max_length=50)),
                ('user', models.CharField(max_length=50)),
                ('diff_content', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Qps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.CharField(default='', max_length=50)),
                ('start_time', models.CharField(default='', max_length=50)),
                ('end_time', models.CharField(default='', max_length=50)),
                ('user', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=0)),
                ('step', models.IntegerField(default=-1)),
                ('testitem', models.IntegerField(default=0)),
                ('newdataip', models.CharField(default='', max_length=500)),
                ('newdatauser', models.CharField(default='', max_length=500)),
                ('newdatapassw', models.CharField(default='', max_length=500)),
                ('newdatapath', models.CharField(default='', max_length=500)),
                ('newdata_topath', models.CharField(default='', max_length=500)),
                ('newconfip', models.CharField(default='', max_length=500)),
                ('newconfuser', models.CharField(default='', max_length=500)),
                ('newconfpassw', models.CharField(default='', max_length=500)),
                ('newconfpath', models.CharField(default='', max_length=500)),
                ('runningIP', models.CharField(default='', max_length=50)),
                ('testsvn', models.TextField(default='')),
                ('basesvn', models.TextField(default='')),
                ('errorlog', models.TextField(default='')),
                ('cost_test', models.TextField(default='')),
                ('cost_base', models.TextField(default='')),
                ('press_qps', models.IntegerField(default=0)),
                ('press_time', models.IntegerField(default=0)),
                ('press_expid', models.IntegerField()),
                ('press_rate', models.FloatField()),
                ('query_ip', models.CharField(default='', max_length=500)),
                ('query_user', models.CharField(default='', max_length=50)),
                ('query_pwd', models.CharField(default='', max_length=50)),
                ('query_path', models.CharField(default='', max_length=500)),
                ('testtag', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='diff',
            name='diff_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webqw.Qps'),
        ),
    ]
