# Generated by Django 2.1 on 2018-08-20 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_auto_20180814_1419'),
        ('webqw', '0002_auto_20180817_1054'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Debug',
            new_name='DebugQw',
        ),
    ]
