# Generated by Django 2.1 on 2018-08-20 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_auto_20180814_1419'),
        ('webqo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Debug_qo',
            new_name='DebugQo',
        ),
    ]
